#!/usr/bin/env bash

# 危安物品登錄資料庫初始化
export PATH=~/bin:/bin:/usr/local/bin:/usr/sbin:/usr/bin
export DATABASE_URL="jdbc:postgresql://localhost/itemdb?user=shun&password=fuck1999"

cd ~/dev/items
duct-items-db-up
lein run :duct/migrator
