#!/usr/bin/env bash

# 危安物品登錄資料庫初始化

export DATABASE_URL="jdbc:postgresql://localhost/itemdb?user=shun&password=fuck1999"

cd /home/shun/dev/items
/home/shun/bin/duct-items-db-up
/home/shun/bin/lein run :duct/migrator
