#!/usr/bin/env bash

# 執行每日mail 危安物品登錄APP紀錄至各單位

export DATABASE_URL="jdbc:postgresql://localhost/itemdb?user=shun&password=fuck1999"

cd /home/shun/dev/items
/home/shun/bin/duct-items-db-up
/home/shun/bin/lein run :items/send-items-daily
